### ISSUE TITLE
Create a workflow

### ISSUE THREAD

**Issue by goelaakash79** [dsckiet/website#1]
@mayanksh99 create a workflow.
* Plan for a folder structure
* Note down the list of libraries/packages we may need.
* and other external stuff that you think is important

**Comment by mayanksh99** [comment]
okay, on it.

**Comment by mayanksh99** [comment]
my-app/
  README.md
  node_modules/
  package.json
  public/
    assets/
      images/
      font/
    index.html
    favicon.ico
  src/
    components/
      Homepage
         Homepage.jsx
         homepage.module.css
     helper/
        theme.js
        global.js
     util/
        routes.js
    App.css
    App.js
    App.test.js
    index.css
    index.js
    logo.svg

**Comment by mayanksh99** [comment]
**Dependencies:** 
react-router-dom
axios
styled-component

**Tools:**
Lottiefiles for animation

**Comment by mayanksh99** [comment]
Further, I will add which we use during development.

**Comment by goelaakash79** [comment]
Okay, looks fine
