### ISSUE TITLE
FAQ redesign

### ISSUE THREAD

**Issue by avi-11** [dsckiet/website#54]
# Overview
 
 Redesign the FAQ page on the website.

# Description

 DSC KIET website is an official website made with HTML, CSS, and JAVASCRIPT. This website describes the organization's workflow, events, and members.

# Expected Outcomes

 A nice, simple-looking UI/UX design for the FAQ page.

# Skills

 UI/UX designing, FIGMA, ADOBE XD, CANVA.

# Possible Mentors

 [Avaneesh Singh](https://github.com/avi-11)

# Expected Time

 2 days

# Difficulty

 easy

**Comment by avi-11** [comment]
# Use This Proposal Template as a Reference to write your own proposal for Msoc

# Your Issue Name

### Your Background and Technical Skills.
<hr>

### What problem are you trying to solve and Your Approach?
<hr>

###  Your Timeline to solve the problem.
<hr>

### Your Commitments.
<hr>

---

**Comment by avi-11** [comment]
# Example of Proposal.


# Improve the generated PDF in the PDF/LaTeX backend

### About me
I have been programming since High School and I have been Advocating for Open-Source projects for the past 2 years. I
have experienced in Python , JavaScript, and Dart[Flutter] and I am currently learning Julia. I organized events on Open-Source in my College and I am the founding member of an Open-Source community [fossc](https://www.saynotocp.org/) where I mentor Students in their Open-Source Journey. For more information about me You can head over to my [website](https://kanishkpachauri.netlify.app/)
<hr>

### Issue - Intermittent CI failures with PDF builds 
Issue - The "PDF/LaTeX backend" stage often fails on CI, causing the docs not to deploy (since they only deploy if that stage passes) Restarting the build usually fixes it though.

## Proposed Solution….
● Fixing any bug on the CI end.
● Debug any issue in the test of the LaTeX backend
● Rewriting guided Tests for it so that it can be fixed throughout the process.
<hr>

###  TimeLine
## May 20 - June 12
Community bonding, understanding Documenter.jl Codebase, re-scoping project implementation/timeline with help from mentors.

## June 13 - June 23
Learning Julia Essentials and other essentials for integration and fixing of issue #1196 and #1467 and #1342 .

## June 24 - July 15
Adding the Proposed Solution for the issue #1196 and #1467

<hr>

### Commitments.
● I’ll try my best to learn everything which is essential for the
project.
● I’ll Create regular Blog posts on the progress of the project
● I’ll try my best to complete the project on time.
● In case of any change in the above timeline, I will inform
the mentors in advance.
<hr>

---

**Comment by Yash-Var** [comment]
> # FAQ redesign 
> # About me
> I'm Yash Varshney . I have experience in  C, C++, HTML, CSS, Python and JavaScript. I am currently doing ReactJS. I am doing open source since 4 month . 
> 
> # Proposed Solution
> I will redesign the FAQ page on the website.
> 
> ## Commitments
> * I will make sure that issue will be resolved as soon as possible.
> * I will try my best to learn everything which is essential for the
>   project.

**Comment by avi-11** [comment]
ok @Yash-Var  you can proceed on to build the functionality.

just read the readme.md and contributing.md to get more knowledge.

I'll assign you the task and you can ask any doubts regarding anything here.

**Comment by Hackintosh-02** [comment]
> # FAQ Redesign
> ### Your Background and Technical Skills.
I am Ashutosh Sharma I am relatively new to Web Designing with around 4 months of experience and I want to start my open source contributions, I have worked on designs on Figma and think I can resolve this issue.
> ### What problem are you trying to solve and Your Approach?
I am trying to solve the issue of redesigning the FAQ page, I will start by changing how the FAQs are presented so there is a clear difference between question and answer for better readability.
> ### Your Timeline to solve the problem.
I am going to start on 11th September and the project will be finished around 13th September.
> ### Your Commitments.
I am committed to giving my all in order to solve this issue ASAP.

**Comment by Jhalakupadhyay** [comment]
> # FAQ REDESIGN
> ### Your Background and Technical Skills.
I am jhalak upadhyay I have been doing app and website designing for last six months , I have also designed an app of my own , I have also been doing logo designing for quite a time and I think I will  surely be able to contribute to the project very well.
> ### What problem are you trying to solve and Your Approach?
I will try to add some colors to the page as it looks bit plain and try to add an aesthetic look to ,try to make use of white spaces to make it look on more of a simpler side.
> ### Your Timeline to solve the problem.
I will start the problem by 12th of September and will complete it by 13th till 11pm.
> ### Your Commitments.
I will put all my efforts to give the page a better look and will complete my work  within the time as I said above and will surely make it look it better with my creativity,

**Comment by disha100** [comment]
# **FAQ REDESIGN**
### Your Background and Technical Skills.
About me 
I am learning front end web development . I have worked with html , CSS ,  JAVASCRIPT . 
I have been a part of design club i.e. MOSAIC club where I have learnt all these required skills for this issue( or say project)  
namely UI/UX designing, FIGMA, ADOBE XD, CANVA. So  I think I can work upon this .

______________________________________________________________________________________________________________________________________

### What problem are you trying to solve and Your Approach?

- TRY TO MAKE IT SIMPLE, CLEAN AND FRESH.
- SIMPLE TO USE.
- MORE INFORMAL AND SOCIABLE.
- MAKE IT LOOK NICER THAN THE PREVIOUS ONE.


______________________________________________________________________________________________________________________________________

### Your Timeline to solve the problem.

- 11 Sep

    -   All planning and plotting collecting more and more ideas and start working .
    -  complete it by 12 Sep.

  


______________________________________________________________________________________________________________________________________
### Your Commitments.

-  I’ll try my best to complete the project on time.

- I will organize the issue in best possible way and put all my efforts.

**Comment by avi-11** [comment]
ok @Jhalakupadhyay  you can proceed on to build the functionality.

just read the readme.md and contributing.md to get more knowledge.

I'll assign you the task and you can ask any doubts regarding anything here.

**Comment by disha100** [comment]
# #54
done
https://www.figma.com/proto/Uq3E1I1D35xdA8aQzMMXev/FAQ-PAGE-REDESIGN?node-id=2%3A3&scaling=scale-down-width&page-id=0%3A1&starting-point-node-id=2%3A3

[FAQ PAGE REDESIGN.zip](https://github.com/dsckiet/website/files/9557171/FAQ.PAGE.REDESIGN.zip)


@avi-11 sir, please review.
